services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: mssql_test
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Teste!@#
    ports:
      - "1433:1433"
    volumes:
      - ~/docker/mssql/data:/var/opt/mssql/data